# dist: xenial

# addons: 
#   sonarcloud:
#     organization: wiyiiong 
#     token:
#       secure: •••••••••••••••• 
# language: python
# cache: pip
# notifications:
#   email: false

# python:
# - 3.8.1
# env:
#   global:
#     - PIPENV_IGNORE_VIRTUALENVS=1

# install:
# - pip install --upgrade pip tox

# script:
# - tox
# - sonar-scanner
 
# jobs:
#   include:
#     - env: TOXENV=py
#     - env: TOXENV=docs
#     - env: TOXENV=style
#     - stage: Crowdin Deployment
#       if: tag IS present OR ENV(BUILD_CROWDIN)
#       python: 3.8.1
#       env:
#         - DEPLOYING=true
#         - TOXENV=py38
#       before_deploy:
#       - curl https://artifacts.crowdin.com/repo/GPG-KEY-crowdin | sudo apt-key add -
#       - echo "deb https://artifacts.crowdin.com/repo/deb/ /" | sudo tee -a /etc/apt/sources.list
#       - sudo apt-get update -qq
#       - sudo apt-get install -y crowdin
#       - pip install redgettext==3.1
#       deploy:
#       - provider: script
#         script: make upload_translations
#         skip_cleanup: true
#         on:
#           repo: Cog-Creators/Red-DiscordBot
#           tags: true

dist: xenial

addons: 
  sonarcloud:
    organization: wiyiiong   
    token:
      secure: •••••••••••••••• 

language: python

cache: pip

notifications:
  email: false

python:
- 3.8.1

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
- pip install --upgrade pip tox
- pip install pytest-mock
- pip install pytest-asyncio
- pip install -e .
- pip install ."[tests]"
- pip install coverage
- pip install setuptools
- pip install pytest-cov

script:
- tox
- py.test --cov=tests tests/ --cov-report xml:coverage.xml
- pytest --junitxml=pytest-report.xml
- sonar-scanner
 
jobs:
  include:
    - env: TOXENV=py
    - env: TOXENV=docs
    - env: TOXENV=style
    - stage: Crowdin Deployment
      if: tag IS present OR ENV(BUILD_CROWDIN)
      python: 3.8.1
      env:
        - DEPLOYING=true
        - TOXENV=py38
      before_deploy:
      - curl https://artifacts.crowdin.com/repo/GPG-KEY-crowdin | sudo apt-key add -
      - echo "deb https://artifacts.crowdin.com/repo/deb/ /" | sudo tee -a /etc/apt/sources.list
      - sudo apt-get update -qq
      - sudo apt-get install -y crowdin
      - pip install redgettext==3.1
      deploy:
      - provider: script
        script: make upload_translations
        skip_cleanup: true
        on:
          repo: Cog-Creators/Red-DiscordBot
          tags: true
